"""Asynchronous pub/sub event bus for internal messaging.

This module provides a simple and efficient event bus for communication
between different modules of the KrakenBot application.

Standard Event Types:
    Market Data Events:
        - market.tick: New tick received
        - market.ohlc: New OHLC candle received
        - market.orderbook: Order book updated

    Trading Events:
        - trade.signal: Trading signal generated by strategy
        - trade.order_placed: Order submitted to exchange
        - trade.order_filled: Order executed
        - trade.order_failed: Order failed to execute
        - trade.order_cancelled: Order was cancelled

    System Events:
        - system.error: System error occurred
        - system.warning: System warning
        - bot.started: Bot started
        - bot.stopped: Bot stopped
        - bot.paused: Bot paused

Example:
    >>> from krakenbot.core.event_bus import EventBus, get_event_bus
    >>> event_bus = get_event_bus()
    >>>
    >>> async def handle_tick(data: dict) -> None:
    ...     print(f"New tick: {data['price']}")
    ...
    >>> await event_bus.subscribe("market.tick", handle_tick)
    >>> await event_bus.publish("market.tick", {"price": "42000.00"})
"""

from __future__ import annotations

import asyncio
from collections import defaultdict
from collections.abc import Callable, Coroutine
from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import Enum
from typing import Any

from krakenbot.core.logger import get_logger

logger = get_logger(__name__)

# Type alias for event callbacks (sync or async)
EventCallback = Callable[[dict[str, Any]], None | Coroutine[Any, Any, None]]


class EventType(str, Enum):
    """Standard event types for the event bus.

    These are pre-defined event types used throughout the application.
    Custom event types can also be used as strings.
    """

    # Market data events
    MARKET_TICK = "market.tick"
    MARKET_OHLC = "market.ohlc"
    MARKET_ORDERBOOK = "market.orderbook"

    # Trading events
    TRADE_SIGNAL = "trade.signal"
    TRADE_ORDER_PLACED = "trade.order_placed"
    TRADE_ORDER_FILLED = "trade.order_filled"
    TRADE_ORDER_FAILED = "trade.order_failed"
    TRADE_ORDER_CANCELLED = "trade.order_cancelled"

    # System events
    SYSTEM_ERROR = "system.error"
    SYSTEM_WARNING = "system.warning"
    BOT_STARTED = "bot.started"
    BOT_STOPPED = "bot.stopped"
    BOT_PAUSED = "bot.paused"


@dataclass
class Event:
    """Represents a published event.

    Attributes:
        event_type: Type of the event.
        data: Event payload data.
        timestamp: When the event was created (UTC).
    """

    event_type: str
    data: dict[str, Any]
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))

    def to_dict(self) -> dict[str, Any]:
        """Convert event to dictionary for logging/serialization.

        Returns:
            Dictionary representation of the event.
        """
        return {
            "event_type": self.event_type,
            "data": self.data,
            "timestamp": self.timestamp.isoformat(),
        }


class EventBus:
    """Asynchronous pub/sub event bus for internal messaging.

    The EventBus allows different parts of the application to communicate
    without direct dependencies. Publishers emit events, and subscribers
    receive events they're interested in.

    Features:
        - Async and sync callback support
        - Multiple subscribers per event type
        - Wildcard subscriptions (e.g., "market.*")
        - Event history tracking (optional)
        - Comprehensive logging

    Example:
        >>> bus = EventBus()
        >>> async def handler(data: dict) -> None:
        ...     print(f"Received: {data}")
        >>> await bus.subscribe("test.event", handler)
        >>> await bus.publish("test.event", {"value": 123})
    """

    def __init__(self, keep_history: bool = False, max_history: int = 1000) -> None:
        """Initialize the event bus.

        Args:
            keep_history: Whether to keep event history.
            max_history: Maximum number of events to keep in history.
        """
        # Subscribers organized by event type
        self._subscribers: dict[str, list[EventCallback]] = defaultdict(list)
        # Wildcard subscribers (e.g., "market.*")
        self._wildcard_subscribers: dict[str, list[EventCallback]] = defaultdict(list)
        # Event history (if enabled)
        self._history: list[Event] = []
        self._keep_history = keep_history
        self._max_history = max_history
        # Lock for thread-safe operations
        self._lock = asyncio.Lock()
        # Statistics
        self._stats = {
            "events_published": 0,
            "events_delivered": 0,
            "delivery_errors": 0,
        }

    async def subscribe(
        self,
        event_type: str | EventType,
        callback: EventCallback,
    ) -> None:
        """Subscribe to an event type.

        Args:
            event_type: Type of event to subscribe to.
                        Use "*" suffix for wildcard (e.g., "market.*").
            callback: Function to call when event is published.
                      Can be sync or async.

        Example:
            >>> async def handle_tick(data: dict) -> None:
            ...     print(data)
            >>> await bus.subscribe("market.tick", handle_tick)
            >>> # Wildcard subscription
            >>> await bus.subscribe("market.*", handle_all_market)
        """
        event_str = event_type.value if isinstance(event_type, EventType) else event_type

        async with self._lock:
            if event_str.endswith(".*"):
                # Wildcard subscription
                prefix = event_str[:-2]  # Remove ".*"
                self._wildcard_subscribers[prefix].append(callback)
                logger.debug(
                    "event_bus_wildcard_subscribed",
                    event_prefix=prefix,
                    callback=callback.__name__,
                    subscriber_count=len(self._wildcard_subscribers[prefix]),
                )
            else:
                self._subscribers[event_str].append(callback)
                logger.debug(
                    "event_bus_subscribed",
                    event_type=event_str,
                    callback=callback.__name__,
                    subscriber_count=len(self._subscribers[event_str]),
                )

    async def unsubscribe(
        self,
        event_type: str | EventType,
        callback: EventCallback,
    ) -> bool:
        """Unsubscribe from an event type.

        Args:
            event_type: Type of event to unsubscribe from.
            callback: The callback to remove.

        Returns:
            True if callback was found and removed, False otherwise.
        """
        event_str = event_type.value if isinstance(event_type, EventType) else event_type

        async with self._lock:
            if event_str.endswith(".*"):
                prefix = event_str[:-2]
                subscribers = self._wildcard_subscribers[prefix]
            else:
                subscribers = self._subscribers[event_str]

            try:
                subscribers.remove(callback)
                logger.debug(
                    "event_bus_unsubscribed",
                    event_type=event_str,
                    callback=callback.__name__,
                )
                return True
            except ValueError:
                logger.warning(
                    "event_bus_unsubscribe_not_found",
                    event_type=event_str,
                    callback=callback.__name__,
                )
                return False

    async def publish(
        self,
        event_type: str | EventType,
        data: dict[str, Any],
    ) -> int:
        """Publish an event to all subscribers.

        Events are delivered asynchronously to all subscribers.
        Errors in one subscriber don't affect other subscribers.

        Args:
            event_type: Type of event to publish.
            data: Event payload data.

        Returns:
            Number of subscribers that received the event.

        Example:
            >>> count = await bus.publish("market.tick", {
            ...     "pair": "XBT/EUR",
            ...     "price": "42000.00",
            ...     "volume": "0.5"
            ... })
            >>> print(f"Delivered to {count} subscribers")
        """
        event_str = event_type.value if isinstance(event_type, EventType) else event_type
        event = Event(event_type=event_str, data=data)

        # Store in history if enabled
        if self._keep_history:
            async with self._lock:
                self._history.append(event)
                if len(self._history) > self._max_history:
                    self._history.pop(0)

        # Collect all relevant subscribers
        callbacks: list[EventCallback] = []

        async with self._lock:
            # Direct subscribers
            callbacks.extend(self._subscribers.get(event_str, []))

            # Wildcard subscribers
            for prefix, wildcard_callbacks in self._wildcard_subscribers.items():
                if event_str.startswith(prefix + "."):
                    callbacks.extend(wildcard_callbacks)

        if not callbacks:
            logger.debug(
                "event_bus_no_subscribers",
                event_type=event_str,
            )
            return 0

        # Deliver to all subscribers
        delivered = 0
        self._stats["events_published"] += 1

        for callback in callbacks:
            try:
                result = callback(data)
                # Handle async callbacks
                if asyncio.iscoroutine(result):
                    await result
                delivered += 1
                self._stats["events_delivered"] += 1
            except Exception as e:
                self._stats["delivery_errors"] += 1
                logger.error(
                    "event_bus_callback_error",
                    event_type=event_str,
                    callback=callback.__name__,
                    error=str(e),
                    error_type=type(e).__name__,
                )

        logger.debug(
            "event_bus_published",
            event_type=event_str,
            subscriber_count=len(callbacks),
            delivered_count=delivered,
        )

        return delivered

    async def publish_and_wait(
        self,
        event_type: str | EventType,
        data: dict[str, Any],
        timeout: float | None = None,
    ) -> int:
        """Publish an event and wait for all handlers to complete.

        This is similar to publish() but runs all callbacks concurrently
        using asyncio.gather and can timeout.

        Args:
            event_type: Type of event to publish.
            data: Event payload data.
            timeout: Maximum time to wait for all handlers (seconds).

        Returns:
            Number of subscribers that received the event.

        Raises:
            asyncio.TimeoutError: If timeout is exceeded.
        """
        event_str = event_type.value if isinstance(event_type, EventType) else event_type
        event = Event(event_type=event_str, data=data)

        # Store in history if enabled
        if self._keep_history:
            async with self._lock:
                self._history.append(event)
                if len(self._history) > self._max_history:
                    self._history.pop(0)

        # Collect all relevant subscribers
        callbacks: list[EventCallback] = []

        async with self._lock:
            callbacks.extend(self._subscribers.get(event_str, []))
            for prefix, wildcard_callbacks in self._wildcard_subscribers.items():
                if event_str.startswith(prefix + "."):
                    callbacks.extend(wildcard_callbacks)

        if not callbacks:
            return 0

        # Create tasks for all callbacks
        async def safe_call(cb: EventCallback) -> bool:
            """Safely call a callback and return success status."""
            try:
                result = cb(data)
                if asyncio.iscoroutine(result):
                    await result
                return True
            except Exception as e:
                logger.error(
                    "event_bus_callback_error",
                    event_type=event_str,
                    callback=cb.__name__,
                    error=str(e),
                )
                return False

        tasks = [safe_call(cb) for cb in callbacks]

        if timeout:
            results = await asyncio.wait_for(
                asyncio.gather(*tasks, return_exceptions=True),
                timeout=timeout,
            )
        else:
            results = await asyncio.gather(*tasks, return_exceptions=True)

        self._stats["events_published"] += 1
        delivered = sum(1 for r in results if r is True)
        self._stats["events_delivered"] += delivered
        self._stats["delivery_errors"] += len(results) - delivered

        return delivered

    async def clear_subscribers(self, event_type: str | EventType | None = None) -> None:
        """Clear subscribers for an event type or all events.

        Args:
            event_type: Event type to clear, or None to clear all.
        """
        async with self._lock:
            if event_type is None:
                self._subscribers.clear()
                self._wildcard_subscribers.clear()
                logger.info("event_bus_all_subscribers_cleared")
            else:
                event_str = (
                    event_type.value if isinstance(event_type, EventType) else event_type
                )
                if event_str.endswith(".*"):
                    prefix = event_str[:-2]
                    if prefix in self._wildcard_subscribers:
                        del self._wildcard_subscribers[prefix]
                else:
                    if event_str in self._subscribers:
                        del self._subscribers[event_str]
                logger.info(
                    "event_bus_subscribers_cleared",
                    event_type=event_str,
                )

    def get_subscriber_count(self, event_type: str | EventType | None = None) -> int:
        """Get the number of subscribers.

        Args:
            event_type: Event type to count, or None for total count.

        Returns:
            Number of subscribers.
        """
        if event_type is None:
            count = sum(len(subs) for subs in self._subscribers.values())
            count += sum(len(subs) for subs in self._wildcard_subscribers.values())
            return count

        event_str = event_type.value if isinstance(event_type, EventType) else event_type
        if event_str.endswith(".*"):
            prefix = event_str[:-2]
            return len(self._wildcard_subscribers.get(prefix, []))
        return len(self._subscribers.get(event_str, []))

    def get_history(
        self,
        event_type: str | None = None,
        limit: int | None = None,
    ) -> list[Event]:
        """Get event history.

        Args:
            event_type: Filter by event type, or None for all.
            limit: Maximum number of events to return.

        Returns:
            List of events (most recent last).
        """
        if not self._keep_history:
            return []

        events = self._history
        if event_type:
            events = [e for e in events if e.event_type == event_type]
        if limit:
            events = events[-limit:]
        return events

    def get_stats(self) -> dict[str, int]:
        """Get event bus statistics.

        Returns:
            Dictionary with event statistics.
        """
        return self._stats.copy()

    def reset_stats(self) -> None:
        """Reset event bus statistics."""
        self._stats = {
            "events_published": 0,
            "events_delivered": 0,
            "delivery_errors": 0,
        }


# Global event bus instance
_event_bus: EventBus | None = None


def get_event_bus(keep_history: bool = False) -> EventBus:
    """Get or create the global event bus instance.

    Args:
        keep_history: Whether to keep event history (only used on first call).

    Returns:
        The global EventBus instance.
    """
    global _event_bus
    if _event_bus is None:
        _event_bus = EventBus(keep_history=keep_history)
    return _event_bus


def reset_event_bus() -> None:
    """Reset the global event bus (for testing).

    This should only be used in tests to ensure a clean state.
    """
    global _event_bus
    _event_bus = None
